FROM golang:1.23-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /server ./cmd/server

FROM alpine:latest

WORKDIR /root/

COPY --from=builder /server .
COPY --from=builder /app/config ./config

EXPOSE 8080

CMD ["./server"]
